sudo: required

language: generic

services:
  - docker

before_intall:
  - echo "start creating an image with docker"
  - docker build -t johndoe/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true johndoe/react-app npm run test -- --coverage

after_success:
  - echo "Test success"